// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "hunspelldebug.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(SONNET_HUNSPELL, "kf.sonnet.clients.hunspell", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(SONNET_HUNSPELL, "kf.sonnet.clients.hunspell")
#endif

