// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "core_debug.h"


#if QT_VERSION >= QT_VERSION_CHECK(5, 4, 0)
Q_LOGGING_CATEGORY(SONNET_LOG_CORE, "kf.sonnet.core", QtInfoMsg)
#else
Q_LOGGING_CATEGORY(SONNET_LOG_CORE, "kf.sonnet.core")
#endif

